baseurl: ''
exclude: ['README.md']
permalink: pretty
title: 'Malone Diesel Repair'

google_analytics_id: ""
homepage:
  show_call_box: true
logo:
  mobile: "images/logo/logotransparent.webp"
  desktop: "images/logo/logotransparent.webp"
  desktop_height: "60px"
footer:
  copyright_text: 'Malone Diesel 2021 ©'

seo:
  meta_og_title: "Malone Diesel Repair"
  meta_og_type: "website"
  meta_og_description: "Friendly and Fast Diesel & Automotive Repair in Shreveport-Bossier Area"


collections:
  services:
    output: true
  team:
    output: true

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables
